name: Rust CI

on:
  push:
    branches:
      - "*"

  # trigger workflow manually
  workflow_dispatch:

# don't waste CI time by cancelling previous workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check if code is correctly formatted using cargo fmt 
  check_code_fmt:
    name: Check if code is correctly formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --check

  # Check if code compiles
  check_code_compiles:
    name: Check if code compiles
    needs: [check_code_fmt]
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run cargo build
        run: cargo build --locked

  # Run all rust tests
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [check_code_compiles]
    steps:
      - uses: actions/checkout@v4

      - name: Run cargo test
        run: cargo test

